- xen/arch/arm/domain_build.c
The check in this patch seem to be not obvious: needs more attention
If there is a coproc driver in Xen, but device won't be
used as a coproc for this domain, then just pass it as is
in the DTB.
> HACK:arm/coproc: Fix device pass through

- xen/arch/arm/coproc/coproc.c
- xen/arch/arm/coproc/coproc.h
- xen/arch/arm/coproc/plat/coproc_xxx.c
This fixes "arm/coproc: remove coproc from vcoproc_init parameter's list" #23 
vcoproc_instance structure, passed to vcoproc_init,
already has all the data needed for the vcoproc's init code.
Do not pass coproc and domain and get those from
vcoproc_instance structure.
> arm/coproc: Do not pass coproc and domain to vcoproc_init

- xen/arch/arm/coproc/coproc.c
- xen/arch/arm/coproc/coproc.h
This fixes "arm/coproc: remove vcoproc from the list prior to deinit" #22 
Currently, we deinitialize a vcoproc and then
remove it from the coproc's list. This may lead to race
conditions as vcoproc_deinit and list manipulation are
not both spin lock protected, but the later.
Fix this by first removing vcoproc from the list
and then deinitializing it. Put a note, that
struct list_head vcoproc_elem must not be touched
by any vcoprocs.
> arm/coproc: Fix vcoproc deinitialization order.

- xen/arch/arm/coproc/coproc.c
- xen/arch/arm/coproc/coproc.h
- xen/arch/arm/coproc/plat/coproc_xxx.c
This fixes "arm/coproc: vcoproc_deinit doesn't need domain as its parameter" #32 
We pass vcoproc_instance to vcoproc_deinit which already
has domain in it, so no need to pass domain
explicitly.
> arm/coproc: Do not pass domain to vcoproc_deinit as parameter

- xen/arch/arm/coproc/plat/coproc_xxx.c
- xen/arch/arm/coproc/schedule.c
- xen/arch/arm/coproc/schedule.h
This fixes "Rename vcoproc_sheduler_xxx to vcoproc_scheduler_xxx" #17 
Rename vcoproc_sheduler_xxx to vcoproc_scheduler_xxx.
> arm/coproc: Fix misspeled scheduler

- xen/arch/arm/coproc/coproc.c
This fixes "arm/coproc: re-work cleanup paths" #26 
Use coproc_release if coproc allocation fails.
> arm/coproc: Use coproc_release in case of error

- xen/arch/arm/coproc/coproc.c
coproc_get_vcoproc gets called from MMIO handlers which
code works at the same time as interrupts served.
A deadlock possible when handler is entered, spin lock
acquired and at that same time IRQ is also about to get
locked.
Use spin_lock_irqsave/irqrestore so the race is correctly
handled.
> arm/coproc: Fix: coproc_get_vcoproc must disable interrupts

- xen/arch/arm/coproc/coproc.c
- xen/arch/arm/coproc/coproc.h
- xen/arch/arm/coproc/plat/common.h
- xen/arch/arm/coproc/plat/coproc_xxx.c
- xen/arch/arm/coproc/schedule.c
This allows better control on verbosity ob the debug
messages via debug levels, not binary choice
of on/off.
> SCF: implement different debug levels for coprocs

- xen/arch/arm/coproc/coproc.h
Wrap the dev with bracers to be able to pass a conditional operator inside.
> scf: fix coproc debug printing

- docs/misc/arm/device-tree/scf.txt
- docs/misc/arm/scf.txt
- tools/libxc/include/xenctrl.h
- tools/libxc/xc_domain.c
- tools/libxl/libxl_arm.c
- xen/arch/arm/coproc/coproc.c
- xen/arch/arm/coproc/coproc.h
- xen/arch/arm/coproc/plat/Makefile
- xen/arch/arm/coproc/plat/coproc_xxx.c
- xen/arch/arm/coproc/plat/coproc_xxx/Makefile
- xen/arch/arm/coproc/plat/coproc_xxx/coproc_xxc.c
- xen/arch/arm/coproc/plat/coproc_xxx/coproc_xxx.c
- xen/arch/arm/coproc/plat/coproc_xxx/coproc_xxx.h
- xen/arch/arm/coproc/schedule.c
- xen/arch/arm/coproc/schedule.h
- xen/arch/arm/domain_build.c
- xen/common/device_tree.c
- xen/include/public/domctl.h
- xen/include/xen/device_tree.h
- xen/xsm/flask/hooks.c
This rework covers following bits:
- basically introduces platform, machine, virtual coprocessor abstractions
- basically introduces a platform coprocessor description model
- introduces SCF configuration using device tree nodes only
Also closes following issues:
- #16 
- #20 
- #35 
- #50 
Also discards #52 , because latest version of the documentation is included in this pull request.
> SCF rework

- xen/arch/arm/domain_build.c
Allow accessing IOMEM range(s) of a coproc device if it
is not used by Dom0: currently if Dom0 doesn't use coproc
then IOMEM range(s) of the device are not allowed to be accessed
by other domains which do.
Fix this by permitting access to IOMEM.
> arm/coproc: Allow iomem access to iomem if not used by Dom0

- tools/hotplug/Linux/init.d/xencommons.in
/var/log could be a tmpfs mount point, so create xen subfolder at runtime.
Signed-off-by: Andrii Anisov <andrii_anisov@epam.com>
> tools/hotplug: create XEN_LOG_DIR at runtime

- tools/libxl/libxl_device.c
- tools/libxl/libxl_disk.c
- tools/libxl/libxl_dm.c
- tools/libxl/libxl_internal.c
- tools/libxl/libxl_internal.h
- tools/libxl/libxl_usb.c
Currently driver domain is determined by comparison with libxl
client domain (dom 0). As result libxl treats domain with
beckends as driver domain and handles it differently on destroying:
waits that driver domain removes frontend xen store entries.
The fix is to use presence of local libxl entry to determine
the driver domain.
Signed-off-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>
> libxl: determine driver domain by libxl local entry

- tools/libxl/libxl_domain.c
During domain reboot its configuration is partially reused
to re-create a new domain, but iomem's GFN field for the
iomem is only restored for those memory ranges, which are
configured in form of [IOMEM_START,NUM_PAGES[@GFN], but not for
those in form of [IOMEM_START,NUM_PAGES], e.g. without GFN.
For the latter GFN is reset to 0, but while mapping ranges
to a domain during reboot there is a check that GFN treated
as valid if it is not equal to LIBXL_INVALID_GFN, thus making
Xen to map IOMEM_START to address 0 in the guest's address space.
Workaround it by resseting GFN to LIBXL_INVALID_GFN, so xl
can set proper values for mapping on reboot.
> [HACK] Reset iomem's gfn to LIBXL_INVALID_GFN on reboot

- xen/arch/arm/cpufreq/Makefile
- xen/arch/arm/cpufreq/cpufreq_emu.c
- xen/arch/arm/cpufreq/cpufreq_if.c
- xen/arch/arm/cpufreq/rcar_gen3_thermal.c
- xen/arch/arm/cpufreq/scpi_cpufreq.c
- xen/common/device_tree.c
- xen/include/asm-arm/device.h
- xen/include/xen/device_tree.h
This pull request adds thermal support to Xen. Currently Xen is able to manage only one thermal sensor. It discovers it from device-tree, configures it and controls it's temperature in the runtime.
If THS temperature exceeds limits, Xen performs predefined actions such as CPU throttling and rebooting the whole system. What I would like to say that Xen is a *temporary place* for this stuff. Thermal as well as DVFS will be moved to SCP (ARM TF).
P.S. As Xen assumes that THS it is managing is a CPU thermal sensor, we have to leave in the device-tree THS3 in "enabled state", others must be disabled (already done).
> Add thermal support

- xen/arch/arm/mm.c
Until Android boot to home screen p2m_lookup request sizes distributed as following:
1 - 6945
<= 10 - 340
<= 100 - 455
<= 1000 - 38
<= 2000 - 21
\> 2000 - 117
> Optimize XENMEM_p2m_lookup implementation

- xen/drivers/passthrough/arm/Makefile
- xen/drivers/passthrough/arm/ipmmu-vmsa-plat.c
- xen/drivers/passthrough/arm/ipmmu-vmsa.c
In a nutshell this patch series does:
1. Sync with Linux IPMMU-VMSA driver from rcar-3.5.9 branch to be able to support M3N SoC.
2. Turn on non ALWAYS_ON power domains (A3VP0, A3VC0) for all supported by driver SoCs (H3, M3, M3N). The IPMMU caches that belongs to these power domains do translation for various IPs such as vspb, fcp, etc. 
3. Disable IPMMU TLB cache function of IPMMU caches that belong to non ALWAYS_ON power domain (A3VP0, A3VC0) for H3 and M3N SoCs according to the H/W restriction.
> IPMMU-VMSA updates

- xen/include/public/arch-arm.h
In order to get running guests with access to IO we have to adjust
XEN guest domain memory map to one specific for an exact platform.
In our case R-CAR Gen3 has IO mapped at 0xc0000000 with 1GB size,
so we limit RAM0_SIZE to 2GB at 0x40000000.
Signed-off-by: Andrii Anisov <andrii_anisov@epam.com>
> Adjust guest memory map

- xen/drivers/passthrough/Kconfig
- xen/drivers/passthrough/arm/ipmmu-vmsa.c
Make it possible to configure Xen/IPMMU shared page tables for
Renesas R-Car's H3 v3.0 and M3N boards which have the IPMMU that
does handle stage 2 translation table format and as the result
is able to share P2M with the CPU.
> ipmmu-vmsa: Add CONFIG_RCAR_IPMMU_PGT_IS_SHARED

- tools/include/xen-sys/Linux/gntdev.h
- tools/libs/gnttab/Makefile
- tools/libs/gnttab/gnttab_core.c
- tools/libs/gnttab/gnttab_unimp.c
- tools/libs/gnttab/include/xengnttab.h
- tools/libs/gnttab/libxengnttab.map
- tools/libs/gnttab/linux.c
- tools/libs/gnttab/minios.c
- tools/libs/gnttab/private.h
[ Upstream commit ee8105cabc16 with 4.10 fixes ]
Add support for Linux grant device driver extension which allows
converting existing dma-buf's into an array of grant references
and vise versa. This is only implemented for Linux as other OSes
have no Linux dma-buf support.
Bump gnttab library minor version to 3 (2 for 4.10).
Acked-by: Wei Liu <wei.liu2@citrix.com>
> libgnttab: Add support for Linux dma-buf

- xen/arch/arm/gic.c
- xen/arch/arm/irq.c
- xen/arch/arm/setup.c
- xen/include/asm-arm/gic.h
Handle GSX irq separately from other guest irqs. Now Xen subscribes to
GSX irq and performs all GSX related actions in an extra interrupt handler.
Xen reads both irq counters (host and guest) and injects GSX irqs
to required domains.
Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
> hack: Rewrite injecting GSX irq logic

- xen/arch/arm/irq.c
- xen/arch/arm/vgic.c
We need to take care of injecting GSX irq to guest domains
that run GPU, since host driver doesn't send corresponding event
to guest driver anymore.
The patch was done in a way to inject GSX irq only to guest domains
that really required it. We assume, if domain config file contains
corresponding irq number then most likely it will run GPU.
Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
> xen/arm: Inject GSX irq to all subscribed guest domains

- xen/arch/arm/irq.c
That function has an intended ASSERT(), but asserts are only
effective for debug builds.
Signed-off-by: Andrii Anisov <andrii_anisov@epam.com>
> arm/irq: move irq_get_guest_info call under spinlock

- xen/arch/arm/irq.c
The point is that BUG_ON is fired when rebooting DomD, since no
occupied slot has been found during iterating gsx_guests array.
But nothing wrong happens here, since driver domain is NOT a GSX guest
and as the result gsx_guests array doesn't contain any pointer to it.
If we could recognize driver domain id properly (not just assuming that
driver domain id is always equal to 1) we would add an approprite check
before invoking remove_gsx_guest.
This patch doesn't mean to make reboot DomD feature fully supported,
but at least Xen won't complain about doing that.
Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
> xen/arm: Remove BUG_ON from remove_gsx_guest func

- xen/include/public/memory.h
In order to not cross with nearest future changes in the upstream XEN interface,
shift our specific hypercall number towards the end of XENMEM hypercall numbers
range.
Signed-off-by: Andrii Anisov <andrii_anisov@epam.com>
> public/memory: Shift XENMEM_p2m_lookup hypercall number

- xen/include/public/arch-arm.h
R-Car platforms cannot use SPI 33 for coordinated suspend interrupt
as it is already in use. Select unused one: SPI 97 (#129).
Fixes: dba546c08188 ("libxl: Creating device tree node for DomU guests")
> Fix coord suspend interrupt number for R-Car

- xen/arch/arm/suspend.c
- xen/drivers/passthrough/arm/ipmmu-vmsa-plat.c
- xen/drivers/passthrough/arm/ipmmu-vmsa.c
PR contains backported fixes, cleanup and suspend/resume implementation.
----------
CONFIG_RCAR_DDR_BACKUP (defined in driver for now) enables real backup/restore operations.
All messages being printed during suspend/resume are DEBUG messages.  If you don't want them to be printed just change "loglvl=all" to "loglvl=info" in Xen bootargs.
> [RFC] IPMMU support for S2RAM and others
